version: 2.1

commands:
  get_dependencies:
    steps:
      - checkout
      - run: go mod download

jobs:
  "docker-go117 release":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7d:8b:b0:21:72:1d:36:cf:47:20:7b:a4:f2:b0:d0:fe"
      - get_dependencies
      - run: ./scripts/release/release.sh
  "docker-go117 build":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - get_dependencies
      - run: go build ./...
  "docker-go117 test":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
        environment:
          TF_ACC_TERRAFORM_VERSION: "0.12.26"
    parameters:
      test_results:
        type: string
        default: /tmp/test-results
    steps:
      - get_dependencies
      - run: mkdir -p << parameters.test_results >>/report
      - run:
          command: |
            gotestsum --junitfile << parameters.test_results >>/report/gotestsum-report.xml -- -coverprofile=cover.out ./...
            go tool cover -html=cover.out -o coverage.html
            mv coverage.html << parameters.test_results >>
      - store_artifacts:
          path: << parameters.test_results >>
          destination: raw-test-output
      - store_test_results:
          path: << parameters.test_results >>
  "docker-go117 vet":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - get_dependencies
      - run: go vet ./...
  "docker-go117 gofmt":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - get_dependencies
      - run: ./scripts/gofmtcheck.sh
  "provider-corner integration test":
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - get_dependencies
      - run:
          command: |
            cd ..
            git clone --depth=1 https://github.com/hashicorp/terraform-provider-corner.git
            cd terraform-provider-corner
            echo "replace github.com/hashicorp/terraform-plugin-framework => ../project" >> go.mod
            go mod tidy
            go test ./... -v -run=TestAccFramework

workflows:
  version: 2
  pr:
    jobs:
      - "docker-go117 build"
      - "docker-go117 test":
          requires:
            - "docker-go117 build"
      - "docker-go117 vet":
          requires:
            - "docker-go117 build"
      - "docker-go117 gofmt":
          requires:
            - "docker-go117 build"
      - "provider-corner integration test":
          requires:
            - "docker-go117 build"

  release:
    jobs:
      - "docker-go117 build"
      - "docker-go117 test":
          requires:
            - "docker-go117 build"
      - "docker-go117 vet":
          requires:
            - "docker-go117 build"
      - "docker-go117 gofmt":
          requires:
            - "docker-go117 build"
      - "provider-corner integration test":
          requires:
            - "docker-go117 build"
      - trigger-release:
          filters:
            branches:
              only:
                - main
          type: approval
      - "docker-go117 release":
          filters:
            branches:
              only:
                - main
          requires:
            - trigger-release
            - "docker-go117 test"
            - "docker-go117 vet"
            - "docker-go117 gofmt"
